wikimedia/wikimedia-page-library

- src/transform/RedLinks.js
https://phabricator.wikimedia.org/T169660
> Use `Array.from` to fix Safari/iOS 9 bug.

- .vscode/launch.json
- Force new protocol.
- Fix test glob.
https://code.visualstudio.com/updates/v1_10#_node2-transitioning
https://github.com/Microsoft/vscode/issues/21883
> Fix: VS Code launch config

- readme.md
- Add note on supported ES6 features.
- Update NPM test commands to be a little more terse.
> Doc: describe ES6 support

- changelog.md
- readme.md
- src/transform/CollapseTable.css
- src/transform/CompatibilityTransform.js
- src/transform/ElementUtilities.js
- src/transform/LazyLoadTransform.css
- src/transform/LazyLoadTransform.js
- src/transform/Polyfill.js
- src/transform/RedLinks.js
- src/transform/ThemeTransform.css
- src/transform/ThemeTransform.js
- src/transform/index.js
- test/transform/CompatibilityTransform.test.js
- test/transform/ElementUtilities.test.js
- test/transform/ThemeTransform.test.js
> New: add theming and dark mode

- changelog.md
- src/transform/PlatformTransform.js
- src/transform/index.js
- test/transform/PlatformTransform.test.js
Allow platform-specific CSS rules. This is required for dark mode
support.
Bug: T165415
> New: add platform transform

- src/transform/EditTransform.css
https://phabricator.wikimedia.org/T171355#3495253
> Hide edit pencil on iOS on H3, H4, H5 and H6 on iOS.

- changelog.md
- src/transform/FooterContainer.css
- src/transform/FooterMenu.css
- src/transform/FooterReadMore.css
https://phabricator.wikimedia.org/T169262
Before
After
> Read more text line height with smallest-size system font is too low

- changelog.md
- src/transform/FooterLegal.css
- src/transform/FooterLegal.js
- src/transform/FooterTransformer.js
https://phabricator.wikimedia.org/T172746
Suggestions how to make it better more than welcome 😁
> Add "View in browser" as a footer link

- package.json
'npm version patch' will do this. Wasn't sure if version would get double-bumped...
> Revert version bump.

- changelog.md
- src/transform/ThemeTransform.css
- src/transform/ThemeTransform.js
https://phabricator.wikimedia.org/T180846
`enwiki > Lua (programming language) > Syntax`
> Fix code highlighting theme-ing

- changelog.md
- src/transform/CollapseTable.js
Allows for setting up tables for expand / collapse behavior without initially collapsing them.
> Add adjustTables

- src/transform/ThemeTransform.css
- src/transform/ThemeTransform.js
Per https://github.com/wikimedia/wikimedia-page-library/pull/102#pullrequestreview-79678402
> Use dark code syntax hightlight for new black theme too.

- changelog.md
- src/transform/CollapseTable.css
- src/transform/FooterContainer.css
- src/transform/FooterMenu.css
- src/transform/FooterReadMore.css
- src/transform/ThemeTransform.css
https://phabricator.wikimedia.org/T182726
> Black theme tweaks

- changelog.md
- src/transform/CollapseTable.css
- src/transform/FooterMenu.css
- src/transform/FooterReadMore.css
- src/transform/ThemeTransform.css
https://phabricator.wikimedia.org/T181847#3838774
> More follow-up "black" theme tweaks

- changelog.md
- src/transform/LazyLoadTransform.js
https://phabricator.wikimedia.org/T183288
> Fix image maps

- changelog.md
- src/transform/CollectionUtilities.js
- src/transform/FooterMenu.js
- src/transform/index.js
- test/fixtures/CollectionUtilities.html
- test/transform/CollectionUtilities.test.js
https://phabricator.wikimedia.org/T164309
> New: CollectionUtilities methods for gathering page issues and disambiguation information

- changelog.md
- src/transform/EditTransform.css
https://phabricator.wikimedia.org/T183018#4159272
> Slight adjustments to edit pencil spacing.

- changelog.md
- webpack.config.babel.js
Add workaround for Node.js require usage.
https://github.com/webpack/webpack/issues/6525
> Fix: Webpack Node.js require bug

- src/transform/FooterContainer.css
https://phabricator.wikimedia.org/T183502
Presently this is only used by iOS.
> Update footer heading color, size and spacing

- src/transform/ElementUtilities.js
- src/transform/WidenImage.js
- test/fixtures/WidenImage.html
- test/transform/ElementUtilities.test.js
- test/transform/WidenImage.test.js
https://phabricator.wikimedia.org/T215667
> Fix absolutely positioned image widening bug

- package-lock.json
> update package lock file

- src/transform/CollapseTable.css
https://phabricator.wikimedia.org/T221037
> make tablet landscape collapsed tables work with upstream css

- readme.md
A few solutions to issues I've run into. Hopefully this helps others
as well.
> Dev: Add more hints to the readme

- demo/HeaderTransform.html
Extracted the demo file from #163. Since the actual prod code for the header is not included I commented out the line which creates the header.
> Header demo

- docs/pcs/pcs.md
- src/pcs/c1/Sections.js
- src/pcs/c1/index.js
- src/transform/SectionUtilities.ts
- src/transform/index.js
- test/transform/SectionUtilities.test.js
get section offsets for the TOC passing HTML body element
Bug: [T219909](https://phabricator.wikimedia.org/T219909)
> Introduce Section Utilities

- docs/pcs/pcs.md
- src/pcs/c1/InteractionHandling.js
- src/transform/CollapseTable.js
- src/transform/SectionUtilities.ts
Add `getSelectionInfo` to `pagelib.c1.InteractionHandler`
https://phabricator.wikimedia.org/T228686
> Add getSelectionInfo

- docs/pcs/pcs.md
- src/pcs/c1/Page.js
- test/pcs/c1/Page.test.js
Bug: [T229038](https://phabricator.wikimedia.org/T229038)
> Add getRevision()

- src/transform/FooterReadMore.js
Bug: [T228330](https://phabricator.wikimedia.org/T228330)
> Remove wiki from readmore link

- docs/pcs/pcs.md
- src/pcs/c1/Footer.js
Use a parameter object instead of ordered parameters so we can be more
flexible in the future.
Also recommend clients to pass in the platform and clientVersion here
for better compatibility in the future.
> Change signature for Footer.add()

- src/transform/Sections.css
- src/transform/index.js
> pagelib: add CSS to hide reference list sections

- docs/pcs/pcs.md
- src/pcs/c1/Page.js
- src/transform/CollectionUtilities.js
- src/transform/FooterMenu.js
- src/transform/Sections.css
- test/fixtures/CollectionUtilities.html
- test/pcs/c1/Page.test.js
- test/transform/CollectionUtilities.test.js
- Hide `.hatnote` and `.ambox`
- Collect hatnotes and ambox content to be passed to clients
**Examples from the MOSFET page on enwiki**
Tapping on the Page Issues footer item sends an action with:
```
{
"action": "footer_item_selected",
"data": {
"itemType": "pageIssues",
"payload": [
{
"html": "This section <b>does not <a href=\"./Wikipedia:Citing_sources\" title=\"Wikipedia:Citing sources\">cite</a> any <a href=\"./Wikipedia:Verifiability\" title=\"Wikipedia:Verifiability\">sources</a></b>.  <small class=\"date-container\"><i>(<span class=\"date\">January 2019</span>)</i></small>",
"section": {
"id": 9,
"title": "MOS capacitors and band diagrams",
"anchor": "MOS_capacitors_and_band_diagrams"
}
},
{
"html": "This section <b>does not <a href=\"./Wikipedia:Citing_sources\" …
```
> Fix page issue collection, hide page issues & hatnotes
