wikimedia/wikimedia-page-library

changelog.md, package.json, rollup.config.js
For instance, the "WidenImage.js" transform can then also have a "WidenImage.css" file and NPM will not only build "applib.js" but also "applib.css".
Respective iOS and Android "Gruntfile.js" will need be modified once to digest "node_modules/applib/build/applib.css" in platform appropriate way (to get "applib.css" into respective "assets" directories).
=> Add "rollup-plugin-css-porter" so applib can deliver css too.

package.json
Improve NPM package scripts:
- Use HEAD instead of master since origin/master and master may be
divergent.
- Only lint when committing or publishing since style lints are fine
during development.
- Update description and keywords to mention JavaScript and CSS.
=> Chore: improve NPM package scripts

.eslintrc.yml, src/ElementUtilities.js, test/WidenImage.js
Add rule to prohibit the usage of unnecessary parentheses and fix
offenders.
=> Chore: forbid superfluous parentheses

changelog.md, package.json, readme.md, test/CollapseTable.js, test/ElementUtilities.js, test/WidenImage.js
This patch renames applib to wikimedia-page-library. As part of this
change, breaking build product renames are made for the JavaScript and
CSS outputs and the NPM references are updated. `pagelib` is used in
JavaScript to keep code at a readable balance between bloat and cryptic.
=> Breaking: rename applib to wikimedia-page-library

changelog.md, src/transform/ElementUtilities.js
Some older versions of the Android WebView do not provide the `matches()`
method on its elements. They do, however, provide an equivalent method
called `webkitMatchesSelector()`, and I've also observed a Samsung flavor
of WebView that provides `matchesSelector()`. This patch introduces a
polyfill that tries to use all three of these variations.
This is currently causing a regression where image widening is not working in API <19.
=> Introduce polyfill for matching element with selector.

changelog.md, package.json, src/transform/ElementUtilities.js
- babel-preset-env v1.1.10 → v1.4.0
- Many bug fixes
https://github.com/babel/babel-preset-env/releases/tag/v1.1.11
https://github.com/babel/babel-preset-env/releases/tag/v1.2.0
https://github.com/babel/babel-preset-env/releases/tag/v1.2.1
https://github.com/babel/babel-preset-env/releases/tag/v1.2.2
https://github.com/babel/babel-preset-env/releases/tag/v1.3.0
https://github.com/babel/babel-preset-env/releases/tag/v1.3.3
https://github.com/babel/babel-preset-env/releases/tag/v1.4.0
- babel-register v6.23.0 → v6.24.1
- eslint v3.16.1 → v3.19.0, eslint-config-node-services v2.0.1  → v2.2.1
- New: JSDoc linting, eslint-plugin-jsdoc v3.0.2
- New: ESLint config descends from greater Wikimedia config,
eslint-config-wikimedia v0.3.0
- Many new rules available in ESLint; see release notes …
=> Chore: upgrade dependencies

.eslintrc.yml, src/transform/CollapseTable.js, src/transform/ElementUtilities.js, src/transform/WidenImage.js, test/transform/CollapseTable.js, test/transform/WidenImage.js, test/utilities/FixtureIO.js
Update the ESLint overrides to require parentheses ("()") and curly
braces ("{}") on arrow functions only as needed.
=> Chore: omit needless parentheses and braces on arrow functions

src/transform/WidenImage.js, test/utilities/StyleMocking.js
Specifying that a function has no return value clarifies that it very
likely has side-effects. Add missing `@return {void}` annotations.
=> Doc: add missing JSDoc return types

.vscode/launch.json, package.json
- Remove test/*.js from package configuration. It would be nice to keep
this in case we ever do put tests at the root but Mocha warns that no
tests were found so it's better to remove until needed.
- Add test/**/*.js to VS Code configuration.
=> Fix: package and VS Code test config

.eslintrc.yml
From the docs:
Float values in JavaScript contain a decimal point, and there is no
requirement that the decimal point be preceded or followed by a
number. For example, the following are all valid JavaScript numbers:
var num = .5;
var num = 2.;
var num = -.7;
Although not a syntax error, this format for numbers can make it
difficult to distinguish between true decimal numbers and the dot
operator. For this reason, some recommend that you should always
include a number before and after a decimal point to make it clear the
intent is to create a decimal number.
Since I don't expect to be able to dot off of primitives, I find I never
mistake `1.0` for an object with a property named `0` and this syntax is
too verbose.
http://eslint.org/docs/rules/no-floating-decimal
=> Chore: permit floating-points without leading or trailing numbers

changelog.md, src/transform/CollapseTable.js, test/transform/CollapseTable.test.js
- Breaking: require a Window instead of a Document in the first
parameter of CollapseTable.collapseTables().
- New: emit a `section-toggled` CustomEvent when a table is expanded or
collapsed. This is needed by lazily loaded images to monitor layout
changes.
=> Breaking: emit a `section-toggled` event

changelog.md, rollup.config.js
This appears to add very little to file size and supports <script>
usage which is helpful for desktop usage and testing.
https://github.com/rollup/rollup/wiki/JavaScript-API#format
=> Update: bundle files as a Universal Module Definition

demo/.eslintrc.yml, src/transform/CollapseTable.js, src/transform/ElementUtilities.js, src/transform/Polyfill.js, src/transform/index.js, test/MochaConfiguration.js, test/mocha.opts, test/transform/CollapseTable.test.js, test/transform/ElementUtilities.test.js, test/transform/Polyfill.test.js
- Add CustomEvent polyfill. This is unavailable on Android API 16 AOSP
Nexus S emulator.
- Move ElementUtilties.matchesSelectorCompat() to
Polyfill.matchesSelector(). Anything that has to touch the window as a
global and requires a compatibility shim should probably go in
Polyfill. ElementUtilities wasn't a bad place for this function but
consolidating the hopefully few polyfills we have in one place will
simplify maintenance.
- Standardize how browser globals are initialized for Mocha tests in
MochaConfiguration.
- Use browser environment when linting demo directory which will only
contain webpages.
=> Fix: add CustomEvent polyfill

.browsersync.config.js
The default Browsersync configuration only detects modified files.
Update the configuration to detect newly added files too.
https://browsersync.io/docs/options#option-watchEvents
=> Fix: Browsersync new file monitoring

changelog.md, src/transform/CollapseTable.css
Needed to play nice with more aggressive `baseline` theming approach.
=> Increase collapse table theme selector specificity

demo/ThemeTransform.html
I took a stab at adding a collapse tables checkbox to ControlPanel.html, but ran into some issues. Rather than going down that rabbit hole (since we may refactor this to use iFrame anyway) I just added a quick checkbox to the theme demo so at least I can proof theme changes against table collapsing in mean time.
=> Add collapse tables checkbox to theme demo.

changelog.md, src/transform/ThemeTransform.js
(notice some green parts have appeared in the top row)
=> Fix: some parts of football uniforms not being classified as presuming white background

changelog.md, package.json, src/transform/WidenImage.js
Parsoid HTML image ancestors, unlike in MediaWiki HTML, often specify
height attributes.  These cramp widened images so that they overlap
their captions and one another (https://phabricator.wikimedia.org/T176753). 
Overriding with `height: 'auto'` fixes this issue.
=> Fix: override inline heights in Parsoid HTML

changelog.md, src/transform/CollapseTable.js, test/transform/CollapseTable.test.js
I'd definitely like to further simplify and cleanup this XF, but for now I kept this PR diff minimal.
According to Safari Web Inspector Timelines recording, with this PR, on my iPhone 6s the `collapseTables` transform on `enwiki > Barack Obama` drops from 200 - 220ms to 2 - 8ms :)
=> Remove recursion from table collapse transform

changelog.md, demo/LazyLoadTransform.html, demo/LazyLoadTransformer.html
Use the lazy document when creating new images to avoid a race condition
with the browser for replacing the images with placeholders. Images
created in the lazy document will not be loaded.
=> Fix: lazy load race condition in demos

src/transform/CollapseTable.css
The collapsible tables have a black background which is the same as the
article backround, which is making them hard to discern within the page.
This adds a thin gray border around collapsible tables, per design
discussions, to make the table more discoverable in black mode.
=> Design tweak for collapsing tables in black theme.

src/transform/LazyLoadTransform.js, test/transform/LazyLoadTransform.test.js
[Background](https://github.com/wikimedia/wikipedia-ios/pull/1971#issuecomment-350352888).
https://phabricator.wikimedia.org/T175323
=> Add 3 items to COPY_ATTRIBUTES which are used by iOS.

changelog.md, src/transform/WidenImage.js, test/fixtures/WidenImage.html, test/transform/WidenImage.test.js
On iOS if we used the image widening transform, then used the lazy image loading transform, the image placeholders were not correctly widened. Turned out to be related to image widening not also widening the image anchor, though I'm not quite sure why this only manifests itself on iOS webkit.
[Screenshots and discussion](https://github.com/wikimedia/wikipedia-ios/pull/1971#discussion_r155354570).
https://phabricator.wikimedia.org/T175323
=> Fix image widening with lazy load on iOS

changelog.md, src/transform/FooterReadMore.js
https://phabricator.wikimedia.org/T182631
Noticed save button was missing on read more result for `Raphael_Assunção` on `enwiki > Aljamain Sterling`.
=> Fix title encoding when updating Read More save buttons.

src/transform/FooterReadMore.js, src/transform/WidenImage.js
On iOS, links from the sign post page weren't loading at all. 
Repro steps:
- In Safari, search for Wikipedia Signpost
- Tap the link for the sign post page (https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/Single/2017-12-18)
- Tap through to any of the links on the page
It's entirely possible these fixes are misguided, I just looked in the JS console and added protections around where there were errors for undefined values. After fixing these issues, the links from the signpost page load as expected.
=> Fix for certain pages not getting sections appended

src/.babelrc
Is 4.1 still accurate for Android?
=> Update: bump Babel iOS target version to 10.3 and Android to 4.4

src/transform/CollapseTable.js, test/transform/CollapseTable.test.js
https://phabricator.wikimedia.org/T185249
I began to decompose some overly stuffed methods to make them easier to grok and test.
Also got rid of some string appending.
<table>
<tr>
<td align=center><h2>Before</h2></td>
<td align=center><h2>After</h2></td>
</tr>
<tr>
<td colspan="2" align=center><h3>exclude geo and coords from titles</h3></td>
</tr>
<tr>
<td colspan="2" align=center>dewiki > Hornburg (Mansfelder Land)</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" align=center><h3>exclude ref links</h3></td>
</tr>
<tr>
<td colspan="2" align=center>enwiki > Fairhaven Station > Boardings and alightings</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" align=center><h3>better title extraction</h3></td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td> …
=> Fix: table headers shouldn't include coordinates, reference links

src/transform/RedLinks.js, test/transform/RedLinks.test.js
No longer needed on iOS. (we still use a fragment, but they can be 'enriched' to relay 'createElement' calls to the document on which they were created so the fragment can work as the document parameter for this transform's kickoff method)
=> Breaking: remove 'fragment' parameter from redlinks transform.

package-lock.json, package.json
This patch adds production build output gzipped file size checks to the
test script so that any future efforts, including changes to the
bundler, may only introduce known size differences. Note:
• Initial limits were taken from the present gzipped chunk sizes rounded
up to the 10th of a kibibyte.
• Only production JavaScript and CSS files are checked.
• The package.json bundlesize configuration options should be moved to a
separate file when possible.
https://github.com/siddharthkp/bundlesize/pull/171
• A leading zero is necessary for floating point limits less than one.
Without a leading zero, checks against these limits appear to always
pass.
• bundlesize was not added to dev because it doesn't support any quiet
options and is verbose. Tests are only executed at precommit.
• JEDEC …
=> Chore: add bundlesize test

changelog.md, package.json, readme.md
Rename the NPM `dev` script, which is the script most often used during
development to serve and iterate on the demos, to the canonical `start`.
This change makes the Page Library more like other JavaScript projects
and will decrease friction experienced by project newcomers.
=> Chore: rename NPM `dev` to `start`

changelog.md, src/transform/EditTransform.css
6.0 changed the edit pencil containment a bit. Caused the CSS which hides iOS edit pencils on H3 and above to not behave itself.
=> Hide iOS edit pencils for sections H3 and above.

changelog.md, src/transform/FooterReadMore.js
https://phabricator.wikimedia.org/T193076
( The `Read more` transform is only used by iOS. )
=> Use new parameters for `Read more` wikidata descriptions.

changelog.md, webpack.config.babel.js
Collapsed table borders were missing for sepia and dark themes.
See commit https://github.com/wikimedia/wikimedia-page-library/pull/137/commits/cb7be145bf2b43485b23c5f6a9c20b93680f82f2 message for details. ( caused by https://github.com/wikimedia/wikimedia-page-library/pull/134/commits/94003b970bb599dcf6606df730cd932ec93c3ccb )
=> Fix css regression

changelog.md, package.json, webpack.config.babel.js
6.0.5 (https://github.com/wikimedia/wikimedia-page-library/pull/137) fixed the CSS regression when developing locally, but when 6.0.5 was published the `CollapseTable` css again jumped above the `ThemeTransform` css. Based on the information below I suspect `extract-text-webpack-plugin` is at fault.
So this PR uses `mini-css-extract-plugin` instead of `extract-text-webpack-plugin`, per the recommendations in the comments linked below.
-----
>How can I keep the css order in the css file when I use extract-text-webpack-plugin？
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/200
>...extract-text-webpack-plugin is for webpack3 and older (will not support webpack 4 it seems). They say to move to mini-css-extract-plugin... …
=> Second attempt to fix CSS regression.

package.json, webpack.config.babel.js
Source maps were not generated for debug builds. There seem to be two
issues:
- The setting in the Webpack configuration file does not appear to be
used. It must be specified on the command line.
- cheap-module-eval-source-map doesn't seem to work so use the same
thing as prod, source-map.
=> Fix: generate source maps for debug builds

src/transform/EditTransform.js, test/transform/EditTransform.test.js
In certain cases, we don't actually want specific sections to be editable (whether due to template transclusion, Parsoid oddities, etc), so we'd like to be able to optionally show or hide the edit pencil when building the section header element.
=> Make the edit pencil in section titles optional.

changelog.md, package-lock.json, package.json, src/transform/LazyLoadTransform.ts, tsconfig.json, webpack.config.babel.js
Add (initial and minimal) support for strict JavaScript typing using
TypeScript. This is the bare minimum implementation including a
conversion of one file. Subsequent PRs will piecewise revise the
codebase.
=> Chore: add JavaScript type-checking support

src/transform/LazyLoadTransform.ts, src/transform/LazyLoadTransformer.js
Adds a new method LazyLoadTransformer.collectExistingPlaceholders which
should be used instead of `convertImagesToPlaceholders` if the
placeholders have been created server-side.
The new method `convertImagesToPlaceholders` looks for elements with the placeholder class.
No need to call `convertImagesToPlaceholders`.
Bug: https://phabricator.wikimedia.org/T198668
=> LazyLoadTransformer now can handle existing placeholders

src/transform/ReferenceCollection.js, test/transform/ReferenceCollection.test.js
The reference text collected in ReferenceCollection.js has begun to
improperly include styles included via TemplateStyles, and these are now
being displayed to users in the Android app.
This patch adds 'style' to the list of selectors to strip when compiling
the reference text.
Bug: https://phabricator.wikimedia.org/T206527
=> Remove citation styles

package-lock.json, package.json
Updated with `npm audit fix`.  Resolves the vulnerability described at
https://www.npmjs.com/advisories/725.
=> Update webpack-dev-server to latest (3.1.14)

package.json, src/transform/ThemeTransform.css
https://phabricator.wikimedia.org/T214728
Fixes bug from ticket above.
- works with either `skins.minerva.base.reset` or `skins.minerva.base.styles`
- plays nice with edit pencil transform (my first attempt used `transparent` instead of `unset` and did not play nice)
=> Fix for dark / black theme bug.

src/transform/ThemeTransform.css
Android had a version compatibility issue with 'unset':
https://phabricator.wikimedia.org/T214728
=> Switch previous theme bug fix - 'unset' to 'initial'.

src/transform/CollapseTable.css, src/transform/OrderedList.css, src/transform/index.js
There are changes coming to the upstream CSS that will break the display of reference lists in the apps. It might also break other ordered lists, but haven't found another repro case. This change preemptively overrides that style to ensure it remains unchanged in the apps for now. Context:
https://phabricator.wikimedia.org/T150377#5019102
Screenshots with CSS manually updated to the upstream proposed change:
There are also changes to padding around captions pending, I've added an override for those as well based on this thread: 
https://phabricator.wikimedia.org/T168861#5019022
=> Pre-emptively override upstream CSS changes

src/transform/BodySpacingTransform.ts, src/transform/index.js, test/transform/BodySpacingTransform.test.js
This commit introduces a new transform, called BodySpacingTransform.
It allows client to set margins and padding on the body element of the
given HTML Document.
Bug: https://phabricator.wikimedia.org/T201382
=> Allow client to set margin/padding on body element

package.json
Add `build:debug` script option which tells web pack to use `development` mode. Prevents minification and creates correct source map files.
Info: https://stackoverflow.com/a/46372748
=> add `build:debug` option which correctly builds sourcemaps

src/transform/WidenImage.css
https://phabricator.wikimedia.org/T221033
needed because of upstream css changes
=> fix image widening on landscape tablet 

src/transform/ThemeTransform.css
Undoes the fix for T214728. The negative side effect for this is that
it caused issues with mobile-html.
I don't believe this rule is still needed now that the PCS base CSS
removes most of the unneeded CSS rules from Minerva.
Bug: https://phabricator.wikimedia.org/T217837
=> Remove background-color rule

.gitignore, changelog.md, package-lock.json, package.json
- Re-resolve dependencies and regenerate package-lock with node 10.15.3 and npm 6.4.1. Verified the built output is the same.
- Re-add "engines" entry in the package.json to specify npm version. For development, this isn't enforced but is worth specifying as the package-lock output is different between 6.4.1 and the current npm version 6.9.0. 6.4.1. is specified instead of 6.9.0 because 6.4.1 is bundled with node 10.15.3.
- Add .DS_Store to the .gitignore for easier development on macOS
- Update version to 6.5.0
=> Re-resolve dependencies, update to 6.5.0

src/transform/CollapseTable.css
When adding `display: block` any height mistakenly set in the table CSS is applied, causing the table to be truncated.
https://phabricator.wikimedia.org/T223477
=> Unset any explicit height of collapsible tables

src/transform/CollapseTable.js, test/transform/CollapseTable.test.js
Per https://phabricator.wikimedia.org/T215059#4933826, is not possible to use innerText, this patch is stripping style and script from fragmentHeader instead.
Bug: [T215059](https://phabricator.wikimedia.org/T215059)
=> TemplateStyles CSS appearing in quick facts header

src/pcs/c1/PageMods.js, src/transform/AdjustTextSize.ts, src/transform/index.js, test/transform/AdjustTextSizeTransform.test.js
When native clients load articles via mobile-html, they need to be able
to adjust the font size.
PS: AllTransforms demo coming in a separate patch with some refactoring.
Bug: T222752
=> page library: allow clients to adjust text size

demo/FooterTransformer.html, demo/lib/TransformationControls/addFooterControl.js, docs/pcs/pcs.md, package.json, src/pcs/c1/Footer.js, src/pcs/c1/PageMods.js, src/pcs/c1/index.js, src/transform/FooterContainer.css, src/transform/FooterContainer.js, src/transform/FooterMenu.css, src/transform/FooterReadMore.css, src/transform/FooterReadMore.js
https://phabricator.wikimedia.org/T217352
To test locally with a local instance of restbase running, use:
```
pagelib.c1.PageMods.addFooter(
document,
'Knight Lore',  // articleTitle
[pagelib.c1.Footer.MenuItemType.languages, pagelib.c1.Footer.MenuItemType.lastEdited, pagelib.c1.Footer.MenuItemType.pageIssues, pagelib.c1.Footer.MenuItemType.disambiguation, pagelib.c1.Footer.MenuItemType.talkPage],  // menuItems
{ 
'readMoreHeading': 'Read more',
'menuDisambiguationTitle': 'Similar pages',
'menuLanguagesTitle': 'Available in 9 other languages',
'menuHeading': 'About this article',
'menuLastEditedSubtitle': 'Full edit history',
'menuLastEditedTitle': 'Edited today',
'licenseString': 'Content is available under $1 unless otherwise noted.',
'menuTalkPageTitle': 'View talk page', …
```
=> BREAKING: Add Footer implementation

docs/pcs/pcs.md, src/pcs/c1/Footer.js, src/pcs/c1/InteractionHandling.js, src/pcs/c1/PageMods.js, src/pcs/c1/index.js, src/transform/FooterMenu.js, src/transform/LazyLoadTransform.ts
for dealing with clicks events or other interactions originating in the WebView that need to be propagated to the native side.
For testing:
```
pagelib.c1.InteractionHandling.setInteractionHandler((interaction) => { console.log(JSON.stringify(interaction)) })
```
then do some interactions (click on links, references, images, ...). Observe the output in the web console.
iOS: 
```
(interaction) => { window.webkit.messageHandlers.interaction.postMessage(interaction) }
```
Android:
```
(interaction) => { window.InteractionWebInterface.post(interaction) }
```
QA:
Open example page: http://localhost:6927/en.wikipedia.org/v1/page/mobile-html/Video
```
pagelib.c1.InteractionHandling.setInteractionHandler((interaction) => { console.log(JSON.stringify(interaction)) })
pagelib.c1.Footer.add( …
```
=> New: interaction handlers

demo/DemoArticles/ArticleRef.js, demo/ThemeTransform.html, src/transform/ThemeTransform.css, src/transform/ThemeTransform.js
- If a span has an inline style for the background, preserve the background color by applying the `pagelib_theme_div_do_not_apply_baseline` class
- Set the `color` of `pagelib_theme_div_do_not_apply_baseline` to black since that's the assumed text color from the base css. Without this, the text could be set to a light color on dark themes on the background color that was intended for use with black text.
Before:
After:
=> Fix appearance of spans with specific background color

src/transform/ReferenceCollection.js, test/transform/ReferenceCollection.test.js
https://phabricator.wikimedia.org/T227907
I'm assuming this will work on Android since plain objects are passed in other places
Let me know if there's a better way to do this 🤔
=> mobile-html: DOMRect object from InteractionHandler response cannot be decoded on iOS

docs/pcs/pcs.md, src/pcs/c1/PageMods.js, test/pcs/c1/PageMods.test.js
The old name was misleading and lead to T227783.
Under the covers we only toggle the collapsed/expanded state for all
tables, which is only useful right when the page gets loaded before the
user makes any changes, hence the addition of "Initially".
The default is all tables are collapsed, so if the user wants the tables
expanded areTablesInitiallyExpanded should be set to true.
Bug: https://phabricator.wikimedia.org/T227783
=> Rename areTablesCollapsed to areTablesInitiallyExpanded

docs/pcs/pcs.md
Now that everything is deployed to production it's more likely that
people will use that instead of the local environment.
=> Doc: Make Footer example point to production URL

src/transform/ReferenceCollection.js, test/transform/ReferenceCollection.test.js
It's useful to know what the target link to the reference is for the
reference_clicked event in InteractionHandling.
=> Add href to ReferenceCollection to collectNearbyReferences output

package.json, src/pcs/c1/InteractionHandling.js
- Fix for https://phabricator.wikimedia.org/T228536 , pass `href` similar to other actions. In this case it points to the original `File:` title
- Remove naturalWidth, naturalHeight - not sure this will be reliable and I don't think the clients need it, only the original width and height that's already included CC @sharvaniharan @nambatee 
- Fix for https://phabricator.wikimedia.org/T228535, pass `title` and `text` with `linkClicked`
It looks like the placeholder action doesn't work as it was (it sends a linkClicked event) - feel free to fix that here, otherwise it can be a follow on
=> Pass href with imageClicked action, don't pass natural size. Pass title and text for linkClicked actions

docs/pcs/pcs.md, src/pcs/c1/Page.js, test/pcs/c1/Page.test.js
The document parameter got removed from L10N.localizeLabels()
but not in the call to it from Page.setup().
Also create unit tests to cover this and updated the docs plus some minor formatting.
=> Fix L10N functionality when called from Page.setup()

docs/pcs/pcs.md, src/pcs/c1/Page.js, src/transform/EditTransform.js, test/pcs/c1/Page.test.js, test/transform/EditTransform.test.js
Adds new function Page.setEditButtons(isEditable, isProtected).
Bug: [T228437](https://phabricator.wikimedia.org/T228437)
=> Allow client to specify if and what edit buttons should be shown

src/transform/CollapseTable.js, src/transform/ReferenceCollection.js, test/transform/CollapseTable.test.js, test/transform/EditTransform.test.js
Per Domino's readme file,[1] we should prefer traversing the DOM tree
using The `first/lastChild` and `next/previousSibling` properties rather than
`childNodes`. Doing the latter converts the linked list representation of
the DOM tree structure to an array-based representation, hurting
performance when modifying the tree.
Updated tests that were accessing `childNodes[0]` rather than `firstChild`
as well, to reinforce this.
[1] https://github.com/fgnass/domino#optimization
=> Performance: Prefer firstChild/nextSibling to childNodes

src/transform/ElementUtilities.js
Domino sometimes errors out when attempting to parse malformed style
declarations, and this is crashing in prod. Add a try-catch block to
handle this.
Phab: https://phabricator.wikimedia.org/T229521
=> Fix: Guard against errors in a try-catch block when reading styles

src/transform/CollapseTable.js
Domino sometimes errors out when attempting to parse malformed style
declarations, and this is crashing in prod. Add a try-catch block to
handle this.
Phab: https://phabricator.wikimedia.org/T229521
=> Fix: Guard against errors when reading styles in CollapseTable.js

docs/pcs/pcs.md, src/pcs/c1/InteractionHandling.js, src/pcs/c1/Page.js, test/pcs/c1/Page.test.js
Moves the scripts from https://gerrit.wikimedia.org/r/c/mediawiki/services/mobileapps/+/534531 into the page library. This allows them to use the `InteractionHandling` abstraction directly for sending events and reduces the number of scripts the page needs to load.
After this is merged and released, an update to mobileapps services will follow to change the body scripts to:
`<script>pagelib.c1.Page.onBodyStart();</script>`
and
`<script defer="true">pagelib.c1.Page.onBodyEnd();</script>`
https://phabricator.wikimedia.org/T233253
=> Add onBodyStart() and onBodyEnd() to pagelib

src/pcs/c1/Page.js, test/pcs/c1/Page.test.js
Incorporates the TOC building function that currently exists in PCS
in lib/metadata.js.
Bug: https://phabricator.wikimedia.org/T230035
=> Add getTableOfContents function to pcs Page module

src/pcs/c1/Page.js, test/pcs/c1/Page.test.js
Fixes an issue caused by a structural difference between raw Parsoid
HTML and PCS mobile-html. In Parsoid HTML, a section's heading element is
always the first child of a section element, but in mobile-html it's
wrapped in an enclosing div.
=> Fix: Get the section header element correctly

changelog.md, src/transform/FooterMenu.js
Setting the accessibility role will allow VoiceOver users to select the entire footer item, instead of having to select individual labels
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/AccessibilityRoles.html
=> Set accessibility role for footer items

src/transform/CollapseTable.js, src/transform/EditTransform.js, src/transform/LazyLoadTransform.ts, src/transform/ThemeTransform.js
Expose methods to operate on individual elements instead of the entire document. This way, the  mobileapps service can walk the DOM once and pass the appropriate elements to the page library for manipulation instead of having the page library perform a `querySelector` for every transform.
This needs to be merged and released before the [corresponding mobileapps change](https://gerrit.wikimedia.org/r/c/mediawiki/services/mobileapps/+/544936) can be merged.
=> Expose new functions to improve mobile-html perf

src/pcs/c1/Page.js, src/transform/ThemeTransform.css, src/transform/ThemeTransform.js
https://phabricator.wikimedia.org/T229286
`classifyElements` is by far the slowest part of preparing `mobile-html`. It's not sustainable to keep adding exclusions to the list of specific [filenames](https://github.com/wikimedia/wikimedia-page-library/blob/master/src/transform/ThemeTransform.js#L44-L45) and [query selectors](https://github.com/wikimedia/wikimedia-page-library/blob/master/src/transform/ThemeTransform.js#L83-L98). 
I'm proposing we add `notheme` and request editors add it to the appropriate templates ahead of the launch of `mobile-html`. This will allow the `mobile-html` endpoint to stop calling `classifyElements`. There is some precedent for this with `nomobile` (now obviated by TemplateStyles) but will need to confirm that this is a viable option.
=> Add 'notheme'

src/pcs/c1/L10N.js, src/transform/LazyLoadTransformer.js, src/transform/SectionUtilities.ts
Fixes incompatibility with parsoid visual diff browser
=> Use Polyfill instead of Array.from to get an array from querySelectorAll
